### PR TITLE
Get Starfish into a minimal working state.

### PR DESCRIPTION
**Pull request by GeoffTearle**
### Description
This PR is the second of two to get Starfish into a minimal working state.

There are a few other small changes to bring Starfish into alignment with Telescope, I.E updating the readme, I hope that's OK.

All changes have been manually tested by myself on an Xperia XA2 running Sailfish 4, connected to a lennok smart watch running an AsteroidOS nightly image.

### Whats working:
* UI is functional
* Able to select watch
* Able to view watch connection state
* Able to view watch battery percentage
* Notifications seem to be sent to the watch most of the time

### Whats not working/implemented:
* Time synchronization between the phone and the watch
* Find my watch
* Weather info
* Music
* Volume

I'll begin to look into adding the missing functionality in subsequent PR's.

### Related Issue
https://github.com/AsteroidOS/starfish/issues/4

PS Thanks heaps for AsteroidOS!!!

### CODE REVIEW

**Comment by jrtberlin** [comment]
Thank you for working on Starfish!
Your changes look reasonable to me and thank you for the longer commit messages. The only question I have is: Why did you downgrade `QtQuick` from 2.2 to 2.0?

**Comment by GeoffTearle** [comment]
Apologies, that was likely an accidental change from when I was trying to get starfish to package correctly.

I re-created the harbour-starfish project from a project template in the Sailfish IDE, and was moving thing over bit by bit to see what was causing it not to work.

I believe that the template was using `QtQuick` 2.0, I'm more than happy to go and revert this change as I don't believe that it is necessary.

**Comment by GeoffTearle** [comment]
I've reverted this downgrade, and and made the project use `QtQuick` 2.2 consistently throughout the project.

**Comment by GeoffTearle** [comment]
Here are some screenshots of the UI

Screenshot_20210319_001

Screenshot_20210319_003


Screenshot_20210319_004

Screenshot_20210319_005

Screenshot_20210319_006

**Comment by jrtberlin** [comment]
Thank you for the `QtQuick` update!
The screenshots do look nice! (Makes me want to retry sailfish on a secondary phone.)

btw: are you on IRC or Matrix?

**Comment by GeoffTearle** [comment]
I'm not currently on either, but I'd be happy to look at joining

**Comment by ncartron** [comment]
wow, i missed that - thanks @GeoffTearle - is there a way to provide the RPM file so that I can try it out on my XA2 - it's running SFOS 4.1 though - will it work?

**Comment by GeoffTearle** [comment]
Hey @ncartron, unfortunately there's currently an incompatibility between the versions of bluez5 that are used on AsteriodOS and SailfishOS (4.0, & 4.1) :( 

Currently Sailfish is using bluez5 5.54 which has a flaw in the code that caches GATT information.
This results in the bluetoothd service segfaulting, on the phone, when you try to connect your watch.

This should be resolved in the next SailfishOS update as they have recently upgraded their bluez5 fork to 5.58

I've also documented some of this on the Sailfish forums while I was investigating the issue.
https://forum.sailfishos.org/t/xa2-bluetoothd-segfaulting-when-pairing-with-smartwatch/6037/8

**Comment by ncartron** [comment]
thanks @GeoffTearle and sorry for the delay in answering!
OK, so let's wait for SFOS 4.2 then :-)

**Pull request merged**
