### PR TITLE
Convert Starship to support CMake 

### PR DESCRIPTION
**Pull request by GeoffTearle**
Apologies, I somehow managed to close my [previous PR](https://github.com/AsteroidOS/starship/pull/24) so I have recreated it here

This PR converts Starship over to the CMake build system, to bring it into alignment with asteroidsyncservice and other AsteroidOS projects.

This PR is dependent on https://github.com/AsteroidOS/asteroidsyncservice/pull/54 first being merged, so that the submodule can then be updated.

### CODE REVIEW

**Comment by FlorentRevest** [comment]
This now looks good to me but the PR it depends on https://github.com/AsteroidOS/asteroidsyncservice/pull/54 should also have a cleaner git log (without the merge commits etc...)

**Comment by GeoffTearle** [comment]
> This now looks good to me but the PR it depends on [AsteroidOS/asteroidsyncservice#54](https://github.com/AsteroidOS/asteroidsyncservice/pull/54) should also have a cleaner git log (without the merge commits etc...)

Sorry for the long tail on this, I'll try to get it all cleaned up this weekend 😄

**Comment by moWerk** [comment]
> Sorry for the long tail on this,

No reason to apologize at all! So great to see you contributing.
As sailfish users, we are accustomed to waits, aren't we :D
Thank you again.

**Comment by GeoffTearle** [comment]
losing this for now, as its massively out of date.
Will attempt to re-open in the future when I have a bit more time to work on it

**Pull request closed without merging**
